# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python36\Scripts\CoreElectroAnalysis\ui\CoreElectroAnalysisMainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.InitFilePathSetButton = QtWidgets.QToolButton(self.centralwidget)
        self.InitFilePathSetButton.setMinimumSize(QtCore.QSize(0, 30))
        self.InitFilePathSetButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.InitFilePathSetButton.setObjectName("InitFilePathSetButton")
        self.horizontalLayout_3.addWidget(self.InitFilePathSetButton)
        self.InitFilePathField = QtWidgets.QTextEdit(self.centralwidget)
        self.InitFilePathField.setEnabled(True)
        self.InitFilePathField.setMinimumSize(QtCore.QSize(0, 30))
        self.InitFilePathField.setMaximumSize(QtCore.QSize(16777215, 30))
        self.InitFilePathField.setToolTip("")
        self.InitFilePathField.setObjectName("InitFilePathField")
        self.horizontalLayout_3.addWidget(self.InitFilePathField)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.InitDataTable = QtWidgets.QTableWidget(self.centralwidget)
        self.InitDataTable.setMinimumSize(QtCore.QSize(300, 300))
        self.InitDataTable.setMaximumSize(QtCore.QSize(400, 16777215))
        self.InitDataTable.setObjectName("InitDataTable")
        self.InitDataTable.setColumnCount(0)
        self.InitDataTable.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.InitDataTable)
        self.MplWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy)
        self.MplWidget.setMinimumSize(QtCore.QSize(300, 300))
        self.MplWidget.setObjectName("MplWidget")
        self.horizontalLayout_2.addWidget(self.MplWidget)
        self.ToolbarWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToolbarWidget.sizePolicy().hasHeightForWidth())
        self.ToolbarWidget.setSizePolicy(sizePolicy)
        self.ToolbarWidget.setObjectName("ToolbarWidget")
        self.horizontalLayout_2.addWidget(self.ToolbarWidget)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LoadDataButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadDataButton.sizePolicy().hasHeightForWidth())
        self.LoadDataButton.setSizePolicy(sizePolicy)
        self.LoadDataButton.setMinimumSize(QtCore.QSize(0, 30))
        self.LoadDataButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.LoadDataButton.setObjectName("LoadDataButton")
        self.horizontalLayout.addWidget(self.LoadDataButton)
        self.PlotGraphButton = QtWidgets.QToolButton(self.centralwidget)
        self.PlotGraphButton.setMinimumSize(QtCore.QSize(0, 30))
        self.PlotGraphButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.PlotGraphButton.setObjectName("PlotGraphButton")
        self.horizontalLayout.addWidget(self.PlotGraphButton)
        self.Mpl_hide_show_button = QtWidgets.QToolButton(self.centralwidget)
        self.Mpl_hide_show_button.setMinimumSize(QtCore.QSize(0, 30))
        self.Mpl_hide_show_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Mpl_hide_show_button.setCheckable(True)
        self.Mpl_hide_show_button.setObjectName("Mpl_hide_show_button")
        self.horizontalLayout.addWidget(self.Mpl_hide_show_button)
        self.AdjustPorosityMButton = QtWidgets.QToolButton(self.centralwidget)
        self.AdjustPorosityMButton.setMinimumSize(QtCore.QSize(0, 30))
        self.AdjustPorosityMButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.AdjustPorosityMButton.setObjectName("AdjustPorosityMButton")
        self.horizontalLayout.addWidget(self.AdjustPorosityMButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InitFilePathSetButton.setText(_translate("MainWindow", "Set file path"))
        self.InitFilePathField.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">C:/Python36/Scripts/CoreElectroAnalysis/data/core_studies_ff.txt</span></p></body></html>"))
        self.LoadDataButton.setText(_translate("MainWindow", "Load data"))
        self.PlotGraphButton.setText(_translate("MainWindow", "Plot data"))
        self.Mpl_hide_show_button.setText(_translate("MainWindow", "Show Hide MPL"))
        self.AdjustPorosityMButton.setText(_translate("MainWindow", "Adjust porosiity-m"))

